services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: form_management_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - form_management_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: form_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: form_management_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: form_management_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - form_management_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - form_management_network

  nginx:
    image: nginx:alpine
    container_name: form_management_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - form_management_network
    depends_on:
      - app

networks:
  form_management_network:
    driver: bridge

volumes:
  form_management_db_data:
    driver: local
